### PR TITLE
Remove drone, replace with Travis

### PR DESCRIPTION
**Pull request by aleccunningham**
Although I love drone it doesn't work all to well for open source, since you have to host it yourself. I replaced it with a travis file that will do the trick -- just remember to switch out the travis user in the README's badge and you should be good to go 👍

### CODE REVIEW

**Comment by aleccunningham** [comment]
Also worth noting that it did come up with a lint error; looked into it, seems like it doesn't like that you are checking the outcome of the err twice?

**Comment by briandowns** [comment]
Hmmm. Interesting. Which linter are you using?

**Comment by aleccunningham** [comment]
https://travis-ci.org/aleccunningham/simple-httpd

```
The command "go vet ./..." exited with 0.
0.23s$ golint $(go list ./...)
/home/travis/gopath/src/github.com/aleccunningham/simple-httpd/certificates.go:170:2: redundant if ...; err != nil check, just return error instead.
```

**Comment by briandowns** [comment]
This is fine to merge. The lint error can be remedied at anytime. You're welcome to put in the PR or I can today. Thanks again for all of this work!

**Pull request merged**
